<section class="home-content">
  <h2>Bienvenue sur Tales&Tape</h2>

    <p>Découvrez un univers captivant de livres et de films soigneusement sélectionnés pour les passionnés de lecture et de cinéma. Chez Tales&Tape, nous croyons au pouvoir des histoires, qu'elles soient racontées à travers les mots ou les images. Que vous soyez à la recherche du dernier bestseller littéraire ou du film culte à savourer, nous avons ce qu'il vous faut.</p>

<h2>Nos collections</h2>
    <ul>Livres : Romans, essais, thrillers, science-fiction, fantasy, et bien plus. Plongez dans des récits inoubliables et laissez-vous transporter par l'imagination des plus grands auteurs.</ul>
    <ul>Films : Blockbusters, classiques intemporels, documentaires, et films indépendants. Vivez des expériences cinématographiques riches et variées.</ul>
    
<h2>Pourquoi choisir Tales&Tape ?</h2>
    <ul>Sélection de qualité : Nous choisissons soigneusement chaque produit pour vous offrir le meilleur.</ul>
    <ul>Expérience client optimale : Commandez facilement et recevez vos livres et films rapidement, chez vous ou en ligne.</ul>
    <ul>Offres exclusives : Profitez de nos promotions régulières et de recommandations personnalisées.</ul>    

<h2>Nouveautés et coups de cœur</h2>
    <p>Chaque semaine, nous vous proposons une sélection de nouveautés et de coups de cœur pour vous inspirer.</p>
</section>    